### ISSUE TITLE
fråga om verifiering

### ISSUE THREAD

**Issue by RealButterbee** [inda21plusplus/ollestra-chess#1]
Detta är ingen riktig issue, utan mer en fråga om hur jag korrekt ska verifiera ett move :) 

Det jag testat är att skapa två nya squares: en där pjäsen står, och en där jag vill flytta den.
Sen har jag gjort en game::board::calculate_moves för den första squaren. Sen verifierar jag genom att kolla att den andra squaren finns med i den vector som kommer tillbaka, och det är då ett giltigt move.

Detta verkar funka för pawns och knights, men inte för diagonala pjäser, och inte för elimineringar, så jag misstänker att det inte är korrekt sätt att verifera på? 

skulle jag kunna få ett kort exempel på hur du använt koden för att verifiera moves? :)

**Comment by OlleStrand** [comment]
Meningen var att `game::move_piece` funktionen skulle göra detta. Men den funkar inte i tillfället så gör på detta sätt istället:

För att räkna ut alla drag samt vilka squares som är farliga att gå på använder man `game::board::calculate_all_moves` som kommer ge en array `[Vec<i8>; 64]` på moves som funkar att ta. Den är uppbyggd av vektorer som i sin tur är index för vilken square du kan gå till. Exempelvis:
```rust
let index_1 = 8i8;
let index_2 = 16i8;
let moves = game.board.calculate_all_moves();

if moves[index_1].contains(index_2) {
    game.make_move(Square::from_i8(index_1), Square::from_i8(index_2));
}
```
Man måste alltså räkna ut alla drag varje gång för att uppdatera vilka positioner som är farliga. Jag har planer att flytta ut uträkningen av farliga squares men så långt har jag inte hunnit.

**Comment by RealButterbee** [comment]
Tackar! det verkar funka :)
